
const ADD_PRODUCTO = 'ADD_PRODUCTO';
const SAVE_SHOP = 'SAVE_SHOP';
const SAVE_FAV = 'SAVE_FAV';
const DELETE_SHOP = 'DELETE_SHOP';
const DELETE_FAV = 'DELETE_FAV';
const DELETE = 'DELETE';
const ADD_UNIDAD = 'ADD_UNIDAD_COMPRA';
const DELETE_UNIDAD = 'DELETE_UNIDAD';

export {
  ADD_PRODUCTO,
  SAVE_SHOP,
  SAVE_FAV,
  DELETE_SHOP,
  DELETE_FAV,
  DELETE,
  ADD_UNIDAD,
  DELETE_UNIDAD
};