
const ADD_PRODUCT = 'ADD_PRODUCT';
const SAVE_SHOP = 'SAVE_SHOP';
const SAVE_FAV = 'SAVE_FAV';
const DELETE_SHOP = 'DELETE_SHOP';
const DELETE_FAV = 'DELETE_FAV';
const DELETE = 'DELETE';
const ADD_UNITY = 'ADD_UNITY';
const DELETE_UNITY = 'DELETE_UNITY';

export {
  ADD_PRODUCT,
  SAVE_SHOP,
  SAVE_FAV,
  DELETE_SHOP,
  DELETE_FAV,
  DELETE,
  ADD_UNITY,
  DELETE_UNITY
};